image: node:latest

pages:
  cache:
      paths:
      - node_modules/

  script:
  - npm install --global ionic cordova
  - npm install
  - ionic build
  - cp -R www public

  artifacts:
    paths:
    - public
  only:
  - master
